include:
  - project: 'cicd/templates/default_template'
    file: '/workflow/standalone_deb.yml'
    ref: dev_dist

prepare:
  extends: .workflow:standalone_deb:prepare
  variables:
    VERSION_FILE: "./VERSION" 
    RELEASE_NOTE_FILE: "./RELEASENOTE.md"
    PRODUCT_NAME: "qomolo_utils"

build:
  extends: .workflow:standalone_deb:build
  variables:
    DOCKERFILE_PATH: "./"
    VERSION_FILE: "./VERSION"
    PRODUCT_NAME: "qomolo_utils"
  image:
    name: harbor.qomolo.com/ros2/foxy/foxy-deepstream
  script:
    - echo "build"
    - source /opt/ros/foxy/setup.bash
    - colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE='-O3'
  artifacts:
    name: "release_info"
    paths:
      - .release_info/
      - "./install/"
      - "SELF_DEBIAN"
  dependencies:
    - prepare

deb_pkg:
  extends: .workflow:standalone_deb:deb_pkg
  variables:
    PRODUCT_NAME: "qomolo_utils"
    PACKAGE_PREFIX: ""
    PACKAGE_NAME: "qomolo-foxy-compressed-pointcloud-transport"
    PACKAGE_INSTALL_PATH: "/opt/qomolo/ros-foxy/compressed-pointcloud-transport/"
    PACKAGE_MAINTAINER: "baolong.wang@westwell-lab.com"
    PACKAGE_DESCRIPTION: "This is a qomolo ros pointcloud compress & decompress package"
    DISTRIBUTION: ${SET_DISTRIBUTION}
    DEB_REPO_URL: "https://repo.qomolo.com/repository/alpha/"
    PACKAGE_ARCHITECTURE: ${SET_ARCHITECTURE}
  stage: deb_pkg
  artifacts:
    name: "release_info"
    paths:
      - .release_info/
      - "*.deb"
  dependencies:
    - build
  parallel:
      matrix:
        - SET_ARCHITECTURE: ["amd64"]
          SET_DISTRIBUTION: ["focal"]

archive:
  extends: .workflow:standalone_deb:archive
  variables:
# 8. upload the *.deb to our archive server
    FILE_LIST: "*.deb"
    PRODUCT_NAME: "qomolo_utils"
  stage: archive
  artifacts:
    name: "release_info"
    paths:
      - .release_info/
      - "*.deb"
  dependencies:
    - deb_pkg

# deploy:
#   extends: .workflow:distdev_module:deploy
#   variables:
#     PRODUCT_NAME: "qomolo_utils"
#   stage: archive
#   dependencies:
#     - dpkg

# intergration:
#   extends: .workflow:distdev_module:intergration
#   variables:
#     TARGET_PROJECT_ID: "68"
#     PRODUCT_NAME: "qomolo_utils"
#   stage: intergration
#   dependencies:
#     - archive

